{"stats": {"errors": 8, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 8}, "results": [{"classname": "index_test:TestSQLMoreQueries", "name": "test_select_all_dogs_names_in_alphabetical_order", "time": 0.00018405914306640625, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_all_dogs_names_in_alphabetical_order' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 19, in test_select_all_dogs_names_in_alphabetical_order\n    self.assertEqual(table.execute(select_all_dogs_names_in_alphabetical_order()).fetchall(), result)\nNameError: name 'select_all_dogs_names_in_alphabetical_order' is not defined\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_all_female_dogs_name_and_breed", "time": 9.72747802734375e-05, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_all_female_dogs_name_and_breed' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 15, in test_select_all_female_dogs_name_and_breed\n    self.assertEqual(table.execute(select_all_female_dogs_name_and_breed()).fetchall(), result)\nNameError: name 'select_all_female_dogs_name_and_breed' is not defined\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest", "time": 8.392333984375e-05, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 27, in test_select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest\n    self.assertEqual(table.execute(select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest()).fetchall(), result)\nNameError: name 'select_hungry_dogs_name_and_breed_ordered_by_youngest_to_oldest' is not defined\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_name_age_and_temperament_of_oldest_dog", "time": 7.939338684082031e-05, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_name_age_and_temperament_of_oldest_dog' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 31, in test_select_name_age_and_temperament_of_oldest_dog\n    self.assertEqual(table.execute(select_name_age_and_temperament_of_oldest_dog()).fetchall(), result)\nNameError: name 'select_name_age_and_temperament_of_oldest_dog' is not defined\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_name_and_age_of_three_youngest_dogs", "time": 8.726119995117188e-05, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_name_and_age_of_three_youngest_dogs' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 35, in test_select_name_and_age_of_three_youngest_dogs\n    self.assertEqual(table.execute(select_name_and_age_of_three_youngest_dogs()).fetchall(), result)\nNameError: name 'select_name_and_age_of_three_youngest_dogs' is not defined\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest", "time": 7.987022399902344e-05, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 39, in test_select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest\n    self.assertEqual(table.execute(select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest()).fetchall(), result)\nNameError: name 'select_name_and_breed_of_dogs_between_age_five_and_ten_ordered_by_oldest_to_youngest' is not defined\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_nameless_dog", "time": 7.843971252441406e-05, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_nameless_dog' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 23, in test_select_nameless_dog\n    self.assertEqual(table.execute(select_nameless_dog()).fetchall(), result)\nNameError: name 'select_nameless_dog' is not defined\n"}, {"classname": "index_test:TestSQLMoreQueries", "name": "test_select_select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order", "time": 0.00010585784912109375, "type": "error", "errtype": "builtins.NameError", "message": "name 'select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/slieb74/sql-more-queries-lab-nyc-career-ds-062518/test/index_test.py\", line 43, in test_select_select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order\n    self.assertEqual(table.execute(select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order()).fetchall(), result)\nNameError: name 'select_name_age_and_hungry_of_hungry_dogs_between_age_two_and_seven_in_alphabetical_order' is not defined\n"}]}